#!/bin/bash

# check for agreement to EULA
if [ ! -f "$MINECRAFT_HOME/eula.txt" ]; then
    if [ "$EULA" == "true" ]; then
        echo "==> Updating $MINECRAFT_HOME/eula.txt"
        echo "# Generated by Docker" > $MINECRAFT_HOME/eula.txt
        echo "# $(date)" >> $MINECRAFT_HOME/eula.txt
        echo "eula=$EULA" >> $MINECRAFT_HOME/eula.txt
        echo "-----> Done!"
    else
        echo >&2 "You need to agree to the EULA in order to run the server."
        echo >&2 "  (https://account.mojang.com/documents/minecraft_eula)"
        echo >&2 "  Please set the EULA variable."
        exit 1
    fi
fi

# check for OP
if [ -z "$DEFAULT_OP" ]; then
    echo >&2 "Please set DEFAULT_OP to continue booting."
    exit 1
fi

# determine Minecraft version
VERSIONS_URL="https://s3.amazonaws.com/Minecraft.Download/versions/versions.json"
case "$VERSION" in
    'latest')
        VERSION=`curl -sL $VERSIONS_URL | jsawk -n 'out(this.latest.release)'`
    ;;
    'snapshot')
        VERSION=`curl -sL $VERSIONS_URL | jsawk -n 'out(this.latest.snapshot)'`
    ;;
    [1-9]*)
        VERSION=$VERSION
    ;;
    *)
        VERSION=`curl -sL $VERSIONS_URL | jsawk -n 'out(this.latest.release)'`
    ;;
esac

JAR_FILE=${JAR_FILE:-"minecraft_server.$VERSION.jar"}
SERVER_URL="https://s3.amazonaws.com/Minecraft.Download/versions/$VERSION/$JAR_FILE"

# download Minecraft server
if [ ! -f "$MINECRAFT_HOME/minecraft_server.jar" ]; then
    echo "==> Downloading $JAR_FILE"
    curl -sSf $SERVER_URL -o $MINECRAFT_HOME/$JAR_FILE
    if [ $? -ne 0 ]; then
        echo >&2 "Failed downloading $JAR_FILE"
        exit 1
    fi
    mv $JAR_FILE $MINECRAFT_HOME/minecraft_server.jar
    echo "-----> Done!"
fi

# add OP users
if [ ! -f "$MINECRAFT_HOME/ops.json" -a ! -f "$MINECRAFT_HOME/ops.txt.converted" ]; then
    echo "==> Adding $DEFAULT_OP to ops list"

    # ignored in versions after 1.7.8 but will be converted to JSON in
    # later versions
    echo $DEFAULT_OP | awk -v RS=, '{print}' >> $MINECRAFT_HOME/ops.txt

    echo "-----> Done!"
fi

# This simple loop read the template file and writes out the environment
# values to a servers.properties file.
if [ ! -f "$MINECRAFT_HOME/server.properties" ]; then
    echo "==> Adding a properties template"
    while read SETTING
    do
        eval echo $SETTING
    done < /tmp/server.properties.template > $MINECRAFT_HOME/server.properties
    echo "-----> Done!"
fi

# set proper permissions
chown -R abc:abc $MINECRAFT_HOME
